config/routes.rb
TestPro::Application.routes.draw do
  namespace :admin do resources :patients end

  namespace :admin do resources :doctors end

  namespace :admin do resources :tests end

  namespace :admin do resources :test_categories end

  devise_for :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/admin/doctor.rb
class Admin::Doctor < ActiveRecord::Base

  has_many :admin_patients

  validates :code, :first_name, :designation, :cell, :presence => true
  #validates :email, :email => true
  validates :email, :presence => true, :uniqueness => true#, :email_format => true
end

app/controllers/admin/doctors_controller.rb
class Admin::DoctorsController < ApplicationController
  # GET /admin/doctors
  # GET /admin/doctors.xml
  before_filter :authenticate_user!
  def index
    @admin_doctors = Admin::Doctor.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_doctors }
    end
  end

  # GET /admin/doctors/1
  # GET /admin/doctors/1.xml
  def show
    @admin_doctor = Admin::Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_doctor }
    end
  end

  # GET /admin/doctors/new
  # GET /admin/doctors/new.xml
  def new
    @admin_doctor = Admin::Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_doctor }
    end
  end

  # GET /admin/doctors/1/edit
  def edit
    @admin_doctor = Admin::Doctor.find(params[:id])
  end

  # POST /admin/doctors
  # POST /admin/doctors.xml
  def create
    @admin_doctor = Admin::Doctor.new(params[:admin_doctor].merge(:user_id => current_user.id))

    respond_to do |format|
      if @admin_doctor.save
        format.html { redirect_to(@admin_doctor, :notice => 'Doctor was successfully created.') }
        format.xml  { render :xml => @admin_doctor, :status => :created, :location => @admin_doctor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_doctor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/doctors/1
  # PUT /admin/doctors/1.xml
  def update
    @admin_doctor = Admin::Doctor.find(params[:id])

    respond_to do |format|
      if @admin_doctor.update_attributes(params[:admin_doctor])
        format.html { redirect_to(@admin_doctor, :notice => 'Doctor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_doctor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/doctors/1
  # DELETE /admin/doctors/1.xml
  def destroy
    @admin_doctor = Admin::Doctor.find(params[:id])
    @admin_doctor.destroy

    respond_to do |format|
      format.html { redirect_to(admin_doctors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/doctors_helper.rb
module Admin::DoctorsHelper
end

app/views/admin/doctors/_form.html.haml
= form_for @admin_doctor do |f|
  -if @admin_doctor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_doctor.errors.count, "error")} prohibited this admin_doctor from being saved:"
      %ul
        - @admin_doctor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :designation
    = f.text_field :designation
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :cell
    = f.text_field :cell
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :address1
    = f.text_field :address1
  .field
    = f.label :address2
    = f.text_field :address2
  .field
    = f.label :postal
    = f.text_field :postal
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .actions
    = f.submit 'Save'

app/views/admin/doctors/edit.html.haml
%h1 Editing admin_doctor

= render 'form'

= link_to 'Show', @admin_doctor
\|
= link_to 'Back', admin_doctors_path

app/views/admin/doctors/index.html.haml
%h1 Listing admin_doctors

%table
  %tr
    %th Code
    %th First name
    %th Last name
    %th Designation
    %th
    %th
    %th

  - @admin_doctors.each do |admin_doctor|
    %tr
      %td= admin_doctor.code
      %td= admin_doctor.first_name
      %td= admin_doctor.last_name
      %td= admin_doctor.designation
      %td= link_to 'Show', admin_doctor
      %td= link_to 'Edit', edit_admin_doctor_path(admin_doctor)
      %td= link_to 'Destroy', admin_doctor, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Doctor', new_admin_doctor_path

app/views/admin/doctors/new.html.haml
%h1 New admin_doctor

= render 'form'

= link_to 'Back', admin_doctors_path

app/views/admin/doctors/show.html.haml
%p
  %b Code:
  = @admin_doctor.code
%p
  %b First name:
  = @admin_doctor.first_name
%p
  %b Last name:
  = @admin_doctor.last_name
%p
  %b Designation:
  = @admin_doctor.designation
%p
  %b Cell:
  = @admin_doctor.cell
%p
  %b Phone:
  = @admin_doctor.phone
%p
  %b Street 1:
  = @admin_doctor.address1
%p
  %b Address2:
  = @admin_doctor.address2
%p
  %b Postal:
  = @admin_doctor.postal
%p
  %b City:
  = @admin_doctor.city
%p
  %b State:
  = @admin_doctor.state
= link_to 'Edit', edit_admin_doctor_path(@admin_doctor)
\|
= link_to 'Back', admin_doctors_path