config/routes.rb
TestPro::Application.routes.draw do
  namespace :admin do resources :patients end

  namespace :admin do resources :doctors end

  namespace :admin do resources :tests end

  namespace :admin do resources :test_categories end

  devise_for :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/admin/patient.rb
class Admin::Patient < ActiveRecord::Base
  belongs_to :admin_doctor

  attr_accessor :doctor

  def admin_doctor
    @doctor = Admin::Doctor.find(self.admin_doctor_id)
  end

end

app/controllers/admin/patients_controller.rb
class Admin::PatientsController < ApplicationController
  # GET /admin/patients
  # GET /admin/patients.xml
  def index
    @admin_patients = Admin::Patient.all
    @admin_patients.each{|test| test.admin_doctor}
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_patients }
    end
  end

  # GET /admin/patients/1
  # GET /admin/patients/1.xml
  def show
    @admin_patient = Admin::Patient.find(params[:id])
    @admin_patient.admin_doctor
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_patient }
    end
  end

  # GET /admin/patients/new
  # GET /admin/patients/new.xml
  def new
    @admin_patient = Admin::Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_patient }
    end
  end

  # GET /admin/patients/1/edit
  def edit
    @admin_patient = Admin::Patient.find(params[:id])
  end

  # POST /admin/patients
  # POST /admin/patients.xml
  def create
    @admin_patient = Admin::Patient.new(params[:admin_patient])

    respond_to do |format|
      if @admin_patient.save
        format.html { redirect_to(@admin_patient, :notice => 'Patient was successfully created.') }
        format.xml  { render :xml => @admin_patient, :status => :created, :location => @admin_patient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/patients/1
  # PUT /admin/patients/1.xml
  def update
    @admin_patient = Admin::Patient.find(params[:id])

    respond_to do |format|
      if @admin_patient.update_attributes(params[:admin_patient])
        format.html { redirect_to(@admin_patient, :notice => 'Patient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/patients/1
  # DELETE /admin/patients/1.xml
  def destroy
    @admin_patient = Admin::Patient.find(params[:id])
    @admin_patient.destroy

    respond_to do |format|
      format.html { redirect_to(admin_patients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/patients_helper.rb
module Admin::PatientsHelper
end

app/views/admin/patients/_form.html.haml
= form_for @admin_patient do |f|
  -if @admin_patient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_patient.errors.count, "error")} prohibited this admin_patient from being saved:"
      %ul
        - @admin_patient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :refrence_no
    = f.text_field :refrence_no
  .field
    = f.label :initial_name
    = f.text_field :initial_name
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :admin_doctor_id
    = f.text_field :admin_doctor_id
  .field
    = f.label :test_date
    = f.date_select :test_date
  .field
    = f.label :test_delivery_date
    = f.date_select :test_delivery_date
  .field
    = f.label :total_amount
    = f.text_field :total_amount
  .field
    = f.label :advance_payment
    = f.text_field :advance_payment
  .field
    = f.label :is_doctor_received_payment
    = f.check_box :is_doctor_received_payment
  .actions
    = f.submit 'Save'

app/views/admin/patients/edit.html.haml
%h1 Editing admin_patient

= render 'form'

= link_to 'Show', @admin_patient
\|
= link_to 'Back', admin_patients_path

app/views/admin/patients/index.html.haml
%h1 Listing admin_patients

%table
  %tr
    %th Refrence no
    %th Initial name
    %th First name
    %th Last name
    %th Admin doctor
    %th Test date
    %th Test delivery date
    %th Total amount
    %th Advance payment
    %th Is doctor received payment
    %th
    %th
    %th

  - @admin_patients.each do |admin_patient|
    %tr
      %td= admin_patient.refrence_no
      %td= admin_patient.initial_name
      %td= admin_patient.first_name
      %td= admin_patient.last_name
      %td= admin_patient.admin_doctor_id
      %td= admin_patient.test_date
      %td= admin_patient.test_delivery_date
      %td= admin_patient.total_amount
      %td= admin_patient.advance_payment
      %td= admin_patient.is_doctor_received_payment
      %td= link_to 'Show', admin_patient
      %td= link_to 'Edit', edit_admin_patient_path(admin_patient)
      %td= link_to 'Destroy', admin_patient, :confirm => 'Are you sure?', :method => :delete

app/views/admin/patients/new.html.haml
%h1 New admin_patient

= render 'form'

= link_to 'Back', admin_patients_path

app/views/admin/patients/show.html.haml
%p
  %b Refrence no:
  = @admin_patient.refrence_no
%p
  %b Initial name:
  = @admin_patient.initial_name
%p
  %b First name:
  = @admin_patient.first_name
%p
  %b Last name:
  = @admin_patient.last_name
%p
  %b Admin doctor:
  = @admin_patient.doctor.first_name
  = @admin_patient.doctor.last_name
%p
  %b Test date:
  = @admin_patient.test_date
%p
  %b Test delivery date:
  = @admin_patient.test_delivery_date
%p
  %b Total amount:
  = @admin_patient.total_amount
%p
  %b Advance payment:
  = @admin_patient.advance_payment
%p
  %b Is doctor received payment:
  = @admin_patient.is_doctor_received_payment

= link_to 'Edit', edit_admin_patient_path(@admin_patient)
\|
= link_to 'Back', admin_patients_path