config/routes.rb
TestPro::Application.routes.draw do
  namespace :admin do resources :patients end

  namespace :admin do resources :doctors end

  namespace :admin do resources :tests end

  namespace :admin do resources :test_categories end

  devise_for :users

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/admin/test_category.rb
class Admin::TestCategory < ActiveRecord::Base
  has_many :admin_tests

end

app/controllers/admin/test_categories_controller.rb
class Admin::TestCategoriesController < ApplicationController
  # GET /admin/test_categories
  # GET /admin/test_categories.xml
  before_filter :authenticate_user!
  def index
    @admin_test_categories = Admin::TestCategory.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_test_categories }
    end
  end

  # GET /admin/test_categories/1
  # GET /admin/test_categories/1.xml
  def show
    @admin_test_category = Admin::TestCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_test_category }
    end
  end

  # GET /admin/test_categories/new
  # GET /admin/test_categories/new.xml
  def new
    @admin_test_category = Admin::TestCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_test_category }
    end
  end

  # GET /admin/test_categories/1/edit
  def edit
    @admin_test_category = Admin::TestCategory.find(params[:id])
  end

  # POST /admin/test_categories
  # POST /admin/test_categories.xml
  def create
    @admin_test_category = Admin::TestCategory.new(params[:admin_test_category].merge(:user_id => current_user.id))

    respond_to do |format|
      if @admin_test_category.save
        format.html { redirect_to(@admin_test_category, :notice => 'Test category was successfully created.') }
        format.xml  { render :xml => @admin_test_category, :status => :created, :location => @admin_test_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_test_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/test_categories/1
  # PUT /admin/test_categories/1.xml
  def update
    @admin_test_category = Admin::TestCategory.find(params[:id])

    respond_to do |format|
      if @admin_test_category.update_attributes(params[:admin_test_category])
        format.html { redirect_to(@admin_test_category, :notice => 'Test category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_test_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/test_categories/1
  # DELETE /admin/test_categories/1.xml
  def destroy
    @admin_test_category = Admin::TestCategory.find(params[:id])
    @admin_test_category.destroy

    respond_to do |format|
      format.html { redirect_to(admin_test_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/test_categories_helper.rb
module Admin::TestCategoriesHelper
end

app/views/admin/test_categories/_form.html.haml
= form_for @admin_test_category do |f|
  -if @admin_test_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_test_category.errors.count, "error")} prohibited this admin_test_category from being saved:"
      %ul
        - @admin_test_category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :is_active
    = f.check_box :is_active
  .actions
    = f.submit 'Save'

app/views/admin/test_categories/edit.html.haml
%h1 Editing admin_test_category

= render 'form'

= link_to 'Show', @admin_test_category
\|
= link_to 'Back', admin_test_categories_path

app/views/admin/test_categories/index.html.haml
%h1 Listing admin_test_categories

%table
  %tr
    %th Name
    %th Description
    %th Is active
    %th
    %th
    %th

  - @admin_test_categories.each do |admin_test_category|
    %tr
      %td= admin_test_category.name
      %td= admin_test_category.description
      %td= admin_test_category.is_active
      %td= link_to 'Show', admin_test_category
      %td= link_to 'Edit', edit_admin_test_category_path(admin_test_category)
      %td= link_to 'Destroy', admin_test_category, :confirm => 'Are you sure?', :method => :delete

app/views/admin/test_categories/new.html.haml
%h1 New admin_test_category

= render 'form'

= link_to 'Back', admin_test_categories_path

app/views/admin/test_categories/show.html.haml
%p
  %b Name:
  = @admin_test_category.name
%p
  %b Description:
  = @admin_test_category.description
%p
  %b Is active:
  = @admin_test_category.is_active

= link_to 'Edit', edit_admin_test_category_path(@admin_test_category)
\|
= link_to 'Back', admin_test_categories_path